# 00. Fundamentos Pytorch

In [109]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.12.0+cu130


## Introdução a tensores



### Criando tensores

In [110]:
#escalar
escalar = torch.tensor(7)
escalar


tensor(7)

In [111]:
escalar.ndim

0

In [112]:
escalar.item()

7

In [113]:
vetor = torch.tensor([7,7])
vetor

tensor([7, 7])

In [114]:
vetor.ndim

1

In [115]:
vetor.shape

torch.Size([2])

In [116]:
matriz = torch.tensor([[7,8],
                       [9,10]])
matriz

tensor([[ 7,  8],
        [ 9, 10]])

In [117]:
matriz.ndim

2

In [118]:
matriz[1][1]

tensor(10)

In [119]:
matriz.shape

torch.Size([2, 2])

In [120]:
tensor = torch.tensor([[[1,2,3],
                        [3,69,100],
                        [4,1209,91]]])
tensor

tensor([[[   1,    2,    3],
         [   3,   69,  100],
         [   4, 1209,   91]]])

In [121]:
tensor.ndim

3

In [122]:
tensor.shape

torch.Size([1, 3, 3])

In [123]:
tensor[0]


tensor([[   1,    2,    3],
        [   3,   69,  100],
        [   4, 1209,   91]])

### Tensores aleatorios

`fluxo = começar com numeros aleatorios -> olhar os dados -> atualizar os numeros aleatorios-> olhar os dados->atualizar os numeros aleatorios`

In [124]:
aleatorio = torch.rand(3,4)
aleatorio

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [125]:
aleatorio.ndim

2

In [126]:
random_image_size_tensor = torch.rand(size = (224,224,3))#altura,largura,numero de canais
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [127]:
zero = torch.zeros(size = (3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [128]:
zero * aleatorio

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [129]:
one = torch.ones(size = (3,4))

In [130]:
one.dtype

torch.float32

In [131]:
aleatorio.dtype

torch.float32

### Criando tensores com range e tensors-like


In [132]:
um_a_dez = torch.arange(start = 1,end = 11, step = 2)
um_a_dez

tensor([1, 3, 5, 7, 9])

In [133]:
dez_zeros = torch.zeros_like(input = um_a_dez)
dez_zeros

tensor([0, 0, 0, 0, 0])

### Tensors datatypes

**Nota:** tipos de dados de tensores é um dos 3 grandes erros que vou encontrar dentro do pytorch e deep learning:
1. Tensores com tipo de dados errado
2. Tensores com o formato(shape) errado
3. Tensores no "device" errado

In [134]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype = None, #tipo de dados ex:torch.float32
                               device = None, #qual device esta o seu tensor (cpu, cuda)
                               requires_grad = False)#rastrear ou não os gradientes com essas operações de tensores


float_32_tensor

tensor([3., 6., 9.])

In [135]:
float_32_tensor.dtype

torch.float32

In [136]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [137]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [138]:
int_32_tensor = torch.tensor([3,6,8], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [139]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 72.], dtype=torch.float16)

### Obtendo informações dos tensores(atributos dos tensores)

1. Tensores com tipo de dados errado - para obter o dtype de um tensor, podemos usar `tensor.dtype`
2. Tensores com o formato(shape) errado - para obter a forma de um tensor, podemos usar `tensor.shape` 
3. Tensores no "device" errado - para obter o dispositivo de um tensor, podemos usar  `tensor.device`

In [140]:
some_tensor = torch.rand(3,4, dtype = torch.float16)
some_tensor

tensor([[0.5747, 0.9199, 0.3230, 0.8613],
        [0.0919, 0.3103, 0.9536, 0.6001],
        [0.0351, 0.6826, 0.3743, 0.5220]], dtype=torch.float16)

In [141]:
print(some_tensor)
print(f"Tipo de dados do tensor: {some_tensor.dtype}")
print(f"Formato do tensor: {some_tensor.shape}")
print(f"Dispositivo do tensor está em: {some_tensor.device}")

tensor([[0.5747, 0.9199, 0.3230, 0.8613],
        [0.0919, 0.3103, 0.9536, 0.6001],
        [0.0351, 0.6826, 0.3743, 0.5220]], dtype=torch.float16)
Tipo de dados do tensor: torch.float16
Formato do tensor: torch.Size([3, 4])
Dispositivo do tensor está em: cpu


### Manipulando tensores(tensor operations)

Operações de tensores incluem:
* Adição
* Subtração
* Multiplicação(element-wise)
* Divisão
* Multiplicações de matrizes

In [142]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [143]:
tensor * 10

tensor([10, 20, 30])

In [144]:
tensor

tensor([1, 2, 3])

In [145]:
tensor - 10

tensor([-9, -8, -7])

In [146]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [147]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Multiplicação de matrizes

Duas formas principais de realizar a multiplicação em redes neurais e deep learning :
x
1. Element-wise multiplication
2. Multiplicação de matrizes(dot product)

Aqui estao duas regras que tem que ser satisfeitas para a multiplicação de matrizes:
1. As **dimensões internas** tem que combinar:
* `(3,2) @ (3,2)` não funciona
* `(2,3) @ (3,2)` funciona
* `(3,2) @ (2,3)` funciona

2. O resultado das matriz tem o formato das **dimensões externas**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`


In [148]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.9072, 1.2472],
        [0.7958, 1.0683]])

In [149]:
tensor = torch.tensor([1,2,3])

In [150]:
tensor * tensor

tensor([1, 4, 9])

In [151]:
torch.matmul(tensor, tensor)

tensor(14)

In [152]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

value

CPU times: user 743 μs, sys: 181 μs, total: 924 μs
Wall time: 3.07 ms


tensor(14)

In [153]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 64 μs, sys: 0 ns, total: 64 μs
Wall time: 67.2 μs


tensor(14)

### Um dos erros mais comuns em deep learning: erro de formato

In [154]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [155]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [156]:
tensor_B.T # transpondo o tensor_B

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [157]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [158]:
output = torch.matmul(tensor_A, tensor_B.T)
print(f"Formato da saida: {output.shape}")

Formato da saida: torch.Size([3, 3])


### Agregações(min,max,sum,mean) em tensor

In [159]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [160]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [161]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [162]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [163]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Achando a posição do min e max em um tensor


In [164]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [165]:
x.argmin()

tensor(0)

In [166]:
x[0]

tensor(0)

In [167]:
x.argmax()

tensor(9)

In [168]:
x[9]

tensor(90)

### Reshaping, stacking(empilhamento), squeezing e unsqueezing

* Reshape - reformata um tensor de entrada para um formato definido
* View - retorna uma visualização de um tensor de entrada de uma deerminado formato, mas que mantém a memoria original do tensor
* Stacking - combina multiplos tensores um em cima do outro(vstack) ou lado a lado (hstack)
* Squeeze - remove todas as dimensões únicas de um tensor
* unsqueeze - adiciona uma dimensão unica a um tensor de destino
* Permute - retorna uma visualização da entrada com dimensões permutadas(trocadas) de uma determinada maneira

In [169]:
import torch
x = torch.arange(1.,10.)
x.dtype, x.shape

(torch.float32, torch.Size([9]))

In [170]:
# Adiciona dimensão extra
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [171]:
# Mudando a view, em uma view, se voce muda a view, muda tambem o que voce atribuiu a view
z = x.view(9,1)
z , z.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [172]:
z[:, 0] = 5
z, x

(tensor([[5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.]]),
 tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]))

In [173]:
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]]),
 torch.Size([9, 4]))

In [174]:
x_vstack = torch.vstack([x,x,x,x])
x_vstack, x_vstack.shape

(tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5., 5., 5., 5.]]),
 torch.Size([4, 9]))

In [175]:
x_hstack = torch.hstack([x,x,x,x])
x_hstack, x_hstack.shape

(tensor([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]),
 torch.Size([36]))

In [176]:
x_reshaped

tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [177]:
x_reshaped.shape

torch.Size([1, 9])

In [178]:
x_reshaped.squeeze()

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [179]:
x_reshaped.squeeze().shape

torch.Size([9])

In [180]:
x_squeeze = x_reshaped.squeeze()
x_unsqueeze = x_squeeze.unsqueeze(dim = 0)

In [181]:
print(f"Tensor anterior: {x_squeeze}")
print(f"Formato anterior: {x_squeeze.shape}")
print(f"Tensor atual: {x_unsqueeze}")
print(f"Formato atual: {x_unsqueeze.shape}")

Tensor anterior: tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])
Formato anterior: torch.Size([9])
Tensor atual: tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]])
Formato atual: torch.Size([1, 9])


In [182]:
x_original = torch.rand(size = (224,224,3))

x_permuted = x_original.permute(2,0,1)
x_original.shape, x_permuted.shape 

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [183]:
x_original[0,0,0] = 5

x_original[0,0,0], x_permuted[0,0,0]

(tensor(5.), tensor(5.))

### Selecionando dados de tensores com indexação

Indexação em Pytorch é parecido com indexação em Numpy

In [184]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [185]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [186]:
x[0][0]

tensor([1, 2, 3])

In [187]:
x[0][0][0]

tensor(1)

In [188]:
# Usamos : para selecionar todos os valores da dimensao desejada
x[:,0]


tensor([[1, 2, 3]])

In [189]:
x[:,:,1]

tensor([[2, 5, 8]])

In [190]:
x[:,1,1]

tensor([5])

In [191]:
x[0,0,:]

tensor([1, 2, 3])

In [192]:
x

x[0,2,2]



tensor(9)

In [193]:
x
x[:, :, 2]

tensor([[3, 6, 9]])

### Tensores Pytorch e numpy

Numpy é uma biblioteca python cientifica popular 

E por isso, Pytorch tem funionalidade para interagir com ela

* Dados em Numpy(np.array) e querer isso em um tensor Pytorch -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [194]:
# Quando convertemos numpy -> pytorch, o tensor reflete o padrao de dados do numpy(float64), a menos que especificada de outra forma
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [195]:
array.dtype

dtype('float64')

In [196]:
torch.arange(1.0, 8.0).dtype


torch.float32

In [197]:
# Se mudar o valor do array numpy, o que acontecera com o tensor pytorch?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [198]:
# Tensor para array numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [199]:
numpy_tensor.dtype

dtype('float32')

In [200]:
# Mudando o tensor, o que acontece ao "tensor  numpy"?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reprodutibilidade (tentando eliminar o estado aleatorio(random))

Resumindo, como a rede neural aprende é:
`Começar com números aleatórios -> operações de tensores -> atualizar números aleátorios para torná-los melhores representações dos dados -> de novo -> de novo -> de novo...`

Para reduzir a aleatoriedade em redes neurais e Pytorch, tras o conceito de **random seed**

Essencialmente, o que a seed faz é "suavizar" a aleatoriedade


In [201]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.3648, 0.1490, 0.8693, 0.0294],
        [0.5449, 0.0794, 0.2313, 0.2927],
        [0.3386, 0.3708, 0.0831, 0.0944]])
tensor([[0.6568, 0.7708, 0.1053, 0.1467],
        [0.1932, 0.9118, 0.1488, 0.0913],
        [0.4470, 0.2440, 0.5571, 0.1928]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [202]:
# Criando tesnores aleatorios mas reproduziveis
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Executando tensores e objetos Pytorch em GPUs (e fazer calculos mais rapidos)

GPUs = computação mais rapida com números, graças ao CUDA + NVIDIA hardware + Pytorch trabalhando nos bastidores para deixar tudo perfeito

### 1. Obtendo a GPU

1. Fácil - Use o Google Colab para obter uma GPU gratuita(opções de melhora)
2.  Use your own GPU - exige um pouco de configuração e o investimento na compra de uma GPU, tem muitas opções... , veja esse post para ver qual opção adquirir: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Usar computação em nuvem - GCP, AWS, Azure, esses serviços permitem alugar computadores na nuvem e acessá-los

Para 2,3 Pytorch + drivers GPU(CUDA), é necessário um pouco de configuração, para fazer isso, consulte a documentação de configuração do Pytorch



In [203]:
!nvidia-smi

/bin/bash: linha 1: nvidia-smi: comando não encontrado


### 2. Checando o acesso da GPU pelo Pytorch
 

In [204]:
# Checando o acesso a GPU com Pytorch
import torch
torch.cuda.is_available()

False

Para o Pytorch, já que ele é capaz de executar computação na GPU ou CPU é uma pratica recomendada configurar um código independente de dispositivo agnóstico: https://pytorch.org/docs/stable/notes/cuda.html#best-pratices

Executar na GPU se disponível, senão o padrão é CPU

In [205]:
# Configurando o dódigo agnóstico de dispositivo
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cpu'

In [206]:
# Contar o numero de dispositivos
torch.cuda.device_count()

0

### 3. Colocando tensores(e modelos) na GPU

O motivo pelo qual queremos nossoos tensores/modelos na GPU, é porque o uso da GPU resulta em cálculos mais rápidos 


In [207]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [208]:
# Mover o tensor para a GPU(se disponível)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))

### 4. Movendo os tensores de volta para a CPU

In [209]:
# Se o tensor estiver na GPU, nao será possível transformar em Numpy

tensor_on_gpu.numpy()

array([1, 2, 3])

In [210]:
# Para corrigir o problema do tensor na GPU com numpy, podemos primeiro configurá-lo para a CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

tensor_back_on_cpu

array([1, 2, 3])

In [211]:
tensor_on_gpu

tensor([1, 2, 3])

### Exercícios e extra-curricular

In [1]:
#Exercício 1
import torch
a = torch.rand(7,7)
a


tensor([[0.1550, 0.7762, 0.7565, 0.8359, 0.2800, 0.6961, 0.3430],
        [0.7640, 0.8203, 0.3122, 0.7982, 0.8636, 0.0893, 0.2483],
        [0.7322, 0.6375, 0.6715, 0.4274, 0.2987, 0.7051, 0.7137],
        [0.7311, 0.2224, 0.5042, 0.0370, 0.3588, 0.0055, 0.8931],
        [0.8306, 0.1997, 0.9146, 0.1969, 0.1751, 0.6494, 0.9065],
        [0.7472, 0.5954, 0.0494, 0.4681, 0.7331, 0.2178, 0.7691],
        [0.9957, 0.1058, 0.1587, 0.2967, 0.9508, 0.3936, 0.5730]])

In [2]:
b = torch.rand(1,7)
transposto = b.T
print(f"{torch.matmul(a, transposto)}")

tensor([[1.7545],
        [1.4544],
        [1.5182],
        [0.6960],
        [1.2307],
        [1.1970],
        [0.9914]])


In [3]:
SEED = 42
torch.manual_seed(SEED)
c = torch.rand(7,7)
torch.manual_seed(SEED)
d = torch.rand(1,7)
d_t = d.T
print(f"Multiplicação da primeira matriz: {c}")
print(f"Com a segunda matriz transposta: {d_t}")
print(f"Resultado: {torch.matmul(c,d_t)}")



Multiplicação da primeira matriz: tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])
Com a segunda matriz transposta: tensor([[0.8823],
        [0.9150],
        [0.3829],
        [0.9593],
        [0.3904],
        [0.6009],
        [0.2566]])
Resultado: tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])


In [4]:
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(2,3)
torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(2,3)
tensor_reformatado = tensor2.reshape(3,2)
resultado = torch.matmul(tensor1, tensor_reformatado)
print(f"Multiplicação dos tensores: {resultado}")



Multiplicação dos tensores: tensor([[0.1204, 0.3411],
        [0.0666, 0.6596]])


In [13]:
v_max = resultado.max()
v_min = resultado.min()
pos_max = resultado.argmax()
pos_min = resultado.argmin()

print(f"Valor máximo: {v_max}")
print(f"Posição máxima: {pos_max}")
print(f"Valor mínimo: {v_min}")
print(f"Posição do valor mínimo: {pos_min}")


Valor máximo: 0.6596311330795288
Posição máxima: 3
Valor mínimo: 0.06662219762802124
Posição do valor mínimo: 2


In [14]:
torch.manual_seed(7)
random = torch.rand(1,1,1,10)
random2 = random.squeeze()

print(f"Primeiro tensor: {random}")
print(f"Formato do primeiro tensor: {random.shape}")
print(f"Segundo tensor: {random2}")
print(f"Formato do segundo tensor: {random2.shape}")

Primeiro tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Formato do primeiro tensor: torch.Size([1, 1, 1, 10])
Segundo tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Formato do segundo tensor: torch.Size([10])


# 01. Pytorch Workflow


In [15]:
o_que_cobrimos = {1: "data(prepare and load)",
                  2: "criar um modelo",
                  3: "ajustar o modelo aos dados(training)",
                  4: "fazer previsões e avaliar o modelo(inferência)",
                  5: "salvar e carregar um modelo",
                  6: "juntar tudo"}

o_que_cobrimos

{1: 'data(prepare and load)',
 2: 'criar um modelo',
 3: 'ajustar o modelo aos dados(training)',
 4: 'fazer previsões e avaliar o modelo(inferência)',
 5: 'salvar e carregar um modelo',
 6: 'juntar tudo'}

In [16]:
import torch
from torch import nn # nn contém todos os blocos de construção do Pytorch para redes neurais
import matplotlib.pyplot as plt

# Checar a versão do PyTorch
torch.__version__

'2.12.0+cu130'

## 1. Dados (preparando e carregando)

Dados podem ser praticamente qualquer coisa... em machine learning.

* Tabela Excel
* Imagens de qualquer tipo
* Videos (YouTube tem muitos dados...)
* Audios como músicas ou podcasts
* DNA
* Texto

Machine Learning é um jogo de duas partes:
1. Obter dados em uma representação numérica.
2. criar um modelo para aprender padrões nessa representação numérica.

Para mostrar isso, vamos criar alguns dados *conhecidos* usando a formula da regressão linear.

Usaremos a fomula da regressão linear para fazer uma linha reta com **parâmetros** *conhecidos*

In [ ]:
# Criando parâmetros conhecidos
weight = 0.7
bias = 0.3

# Criando dados
start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim = 1)
y = weight * X + bias

X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]),
 50,
 50)

In [21]:
len(X), len(y)

(50, 50)