# 00 Fundamentos Pytorch

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.12.0+cu130


## Introdução a tensores



### Criando tensores

In [7]:
#escalar
escalar = torch.tensor(7)
escalar


tensor(7)

In [8]:
escalar.ndim

0

In [9]:
escalar.item()

7

In [10]:
vetor = torch.tensor([7,7])
vetor

tensor([7, 7])

In [11]:
vetor.ndim

1

In [12]:
vetor.shape

torch.Size([2])

In [13]:
matriz = torch.tensor([[7,8],
                       [9,10]])
matriz

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matriz.ndim

2

In [18]:
matriz[1][1]

tensor(10)

In [19]:
matriz.shape

torch.Size([2, 2])

In [37]:
tensor = torch.tensor([[[1,2,3],
                        [3,69,100],
                        [4,1209,91]]])
tensor

tensor([[[   1,    2,    3],
         [   3,   69,  100],
         [   4, 1209,   91]]])

In [38]:
tensor.ndim

3

In [39]:
tensor.shape

torch.Size([1, 3, 3])

In [40]:
tensor[0]


tensor([[   1,    2,    3],
        [   3,   69,  100],
        [   4, 1209,   91]])

### Tensores aleatorios

`fluxo = começar com numeros aleatorios -> olhar os dados -> atualizar os numeros aleatorios-> olhar os dados->atualizar os numeros aleatorios`

In [43]:
aleatorio = torch.rand(3,4)
aleatorio

tensor([[0.0917, 0.1454, 0.5248, 0.4358],
        [0.5420, 0.3393, 0.3772, 0.2503],
        [0.1660, 0.4024, 0.5282, 0.4281]])

In [44]:
aleatorio.ndim

2

In [47]:
random_image_size_tensor = torch.rand(size = (224,224,3))#altura,largura,numero de canais
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [51]:
zero = torch.zeros(size = (3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [52]:
zero * aleatorio

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
one = torch.ones(size = (3,4))

In [59]:
one.dtype

torch.float32

In [60]:
aleatorio.dtype

torch.float32