# 00 Fundamentos Pytorch

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.12.0+cu130


## Introdução a tensores



### Criando tensores

In [4]:
#escalar
escalar = torch.tensor(7)
escalar


tensor(7)

In [5]:
escalar.ndim

0

In [6]:
escalar.item()

7

In [7]:
vetor = torch.tensor([7,7])
vetor

tensor([7, 7])

In [8]:
vetor.ndim

1

In [9]:
vetor.shape

torch.Size([2])

In [10]:
matriz = torch.tensor([[7,8],
                       [9,10]])
matriz

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matriz.ndim

2

In [12]:
matriz[1][1]

tensor(10)

In [13]:
matriz.shape

torch.Size([2, 2])

In [14]:
tensor = torch.tensor([[[1,2,3],
                        [3,69,100],
                        [4,1209,91]]])
tensor

tensor([[[   1,    2,    3],
         [   3,   69,  100],
         [   4, 1209,   91]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

In [17]:
tensor[0]


tensor([[   1,    2,    3],
        [   3,   69,  100],
        [   4, 1209,   91]])

### Tensores aleatorios

`fluxo = começar com numeros aleatorios -> olhar os dados -> atualizar os numeros aleatorios-> olhar os dados->atualizar os numeros aleatorios`

In [18]:
aleatorio = torch.rand(3,4)
aleatorio

tensor([[0.4839, 0.0955, 0.5678, 0.8052],
        [0.5530, 0.5913, 0.4862, 0.8120],
        [0.7363, 0.1402, 0.5395, 0.9855]])

In [19]:
aleatorio.ndim

2

In [20]:
random_image_size_tensor = torch.rand(size = (224,224,3))#altura,largura,numero de canais
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
zero = torch.zeros(size = (3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zero * aleatorio

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
one = torch.ones(size = (3,4))

In [24]:
one.dtype

torch.float32

In [25]:
aleatorio.dtype

torch.float32

### Criando tensores com range e tensors-like


In [26]:
um_a_dez = torch.arange(start = 1,end = 11, step = 2)
um_a_dez

tensor([1, 3, 5, 7, 9])

In [27]:
dez_zeros = torch.zeros_like(input = um_a_dez)
dez_zeros

tensor([0, 0, 0, 0, 0])

### Tensors datatypes

**Nota:** tipos de dados de tensores é um dos 3 grandes erros que vou encontrar dentro do pytorch e deep learning:
1. Tensores com tipo de dados errado
2. Tensores com o formato(shape) errado
3. Tensores no "device" errado

In [28]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype = None, #tipo de dados ex:torch.float32
                               device = None, #qual device esta o seu tensor (cpu, cuda)
                               requires_grad = False)#rastrear ou não os gradientes com essas operações de tensores


float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,8], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [33]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 72.], dtype=torch.float16)

### Obtendo informações dos tensores(atributos dos tensores)

1. Tensores com tipo de dados errado - para obter o dtype de um tensor, podemos usar `tensor.dtype`
2. Tensores com o formato(shape) errado - para obter a forma de um tensor, podemos usar `tensor.shape` 
3. Tensores no "device" errado - para obter o dispositivo de um tensor, podemos usar  `tensor.device`

In [34]:
some_tensor = torch.rand(3,4, dtype = torch.float16)
some_tensor

tensor([[0.7402, 0.0948, 0.2388, 0.2256],
        [0.1603, 0.1359, 0.7349, 0.1787],
        [0.1013, 0.6221, 0.3057, 0.1238]], dtype=torch.float16)

In [35]:
print(some_tensor)
print(f"Tipo de dados do tensor: {some_tensor.dtype}")
print(f"Formato do tensor: {some_tensor.shape}")
print(f"Dispositivo do tensor está em: {some_tensor.device}")

tensor([[0.7402, 0.0948, 0.2388, 0.2256],
        [0.1603, 0.1359, 0.7349, 0.1787],
        [0.1013, 0.6221, 0.3057, 0.1238]], dtype=torch.float16)
Tipo de dados do tensor: torch.float16
Formato do tensor: torch.Size([3, 4])
Dispositivo do tensor está em: cpu


### Manipulando tensores(tensor operations)

Operações de tensores incluem:
* Adição
* Subtração
* Multiplicação(element-wise)
* Divisão
* Multiplicações de matrizes

In [36]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [37]:
tensor * 10

tensor([10, 20, 30])

In [38]:
tensor

tensor([1, 2, 3])

In [39]:
tensor - 10

tensor([-9, -8, -7])

In [40]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Multiplicação de matrizes

Duas formas principais de realizar a multiplicação em redes neurais e deep learning :
x
1. Element-wise multiplication
2. Multiplicação de matrizes(dot product)

Aqui estao duas regras que tem que ser satisfeitas para a multiplicação de matrizes:
1. As **dimensões internas** tem que combinar:
* `(3,2) @ (3,2)` não funciona
* `(2,3) @ (3,2)` funciona
* `(3,2) @ (2,3)` funciona

2. O resultado das matriz tem o formato das **dimensões externas**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`


In [42]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.8711, 0.8737],
        [1.2055, 1.1598]])

In [43]:
tensor = torch.tensor([1,2,3])

In [44]:
tensor * tensor

tensor([1, 4, 9])

In [45]:
torch.matmul(tensor, tensor)

tensor(14)

In [46]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

value

CPU times: user 644 μs, sys: 101 μs, total: 745 μs
Wall time: 5.63 ms


tensor(14)

In [47]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 151 μs, sys: 36 μs, total: 187 μs
Wall time: 156 μs


tensor(14)

### Um dos erros mais comuns em deep learning: erro de formato

In [48]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [49]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [50]:
tensor_B.T # transpondo o tensor_B

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [51]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [52]:
output = torch.matmul(tensor_A, tensor_B.T)
print(f"Formato da saida: {output.shape}")

Formato da saida: torch.Size([3, 3])


### Agregações(min,max,sum,mean) em tensor

In [53]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [54]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [55]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [56]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [57]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Achando a posição do min e max em um tensor


In [58]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
x.argmin()

tensor(0)

In [60]:
x[0]

tensor(0)

In [61]:
x.argmax()

tensor(9)

In [62]:
x[9]

tensor(90)

### Reshaping, stacking(empilhamento), squeezing e unsqueezing

* Reshape - reformata um tensor de entrada para um formato definido
* View - retorna uma visualização de um tensor de entrada de uma deerminado formato, mas que mantém a memoria original do tensor
* Stacking - combina multiplos tensores um em cima do outro(vstack) ou lado a lado (hstack)
* Squeeze - remove todas as dimensões únicas de um tensor
* unsqueeze - adiciona uma dimensão unica a um tensor de destino
* Permute - retorna uma visualização da entrada com dimensões permutadas(trocadas) de uma determinada maneira

In [63]:
import torch
x = torch.arange(1.,10.)
x.dtype, x.shape

(torch.float32, torch.Size([9]))

In [64]:
# Adiciona dimensão extra
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# Mudando a view, em uma view, se voce muda a view, muda tambem o que voce atribuiu a view
z = x.view(9,1)
z , z.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [66]:
z[:, 0] = 5
z, x

(tensor([[5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.]]),
 tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]))

In [79]:
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]]),
 torch.Size([9, 4]))

In [68]:
x_vstack = torch.vstack([x,x,x,x])
x_vstack, x_vstack.shape

(tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5., 5., 5., 5.]]),
 torch.Size([4, 9]))

In [69]:
x_hstack = torch.hstack([x,x,x,x])
x_hstack, x_hstack.shape

(tensor([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]),
 torch.Size([36]))

In [70]:
x_reshaped

tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [71]:
x_reshaped.shape

torch.Size([1, 9])

In [72]:
x_reshaped.squeeze()

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [73]:
x_reshaped.squeeze().shape

torch.Size([9])

In [74]:
x_squeeze = x_reshaped.squeeze()
x_unsqueeze = x_squeeze.unsqueeze(dim = 0)

In [75]:
print(f"Tensor anterior: {x_squeeze}")
print(f"Formato anterior: {x_squeeze.shape}")
print(f"Tensor atual: {x_unsqueeze}")
print(f"Formato atual: {x_unsqueeze.shape}")

Tensor anterior: tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])
Formato anterior: torch.Size([9])
Tensor atual: tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]])
Formato atual: torch.Size([1, 9])


In [76]:
x_original = torch.rand(size = (224,224,3))

x_permuted = x_original.permute(2,0,1)
x_original.shape, x_permuted.shape 

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [77]:
x_original[0,0,0] = 5

x_original[0,0,0], x_permuted[0,0,0]

(tensor(5.), tensor(5.))

### Selecionando dados de tensores com indexação

Indexação em Pytorch é parecido com indexação em Numpy

In [80]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [81]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [82]:
x[0][0]

tensor([1, 2, 3])

In [83]:
x[0][0][0]

tensor(1)

In [84]:
# Usamos : para selecionar todos os valores da dimensao desejada
x[:,0]


tensor([[1, 2, 3]])

In [85]:
x[:,:,1]

tensor([[2, 5, 8]])

In [86]:
x[:,1,1]

tensor([5])

In [87]:
x[0,0,:]

tensor([1, 2, 3])

In [88]:
x

x[0,2,2]



tensor(9)

In [89]:
x
x[:, :, 2]

tensor([[3, 6, 9]])

### Tensores Pytorch e numpy

Numpy é uma biblioteca python cientifica popular 

E por isso, Pytorch tem funionalidade para interagir com ela

* Dados em Numpy(np.array) e querer isso em um tensor Pytorch -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [90]:
# Quando convertemos numpy -> pytorch, o tensor reflete o padrao de dados do numpy(float64), a menos que especificada de outra forma
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [91]:
array.dtype

dtype('float64')

In [92]:
torch.arange(1.0, 8.0).dtype


torch.float32

In [93]:
# Se mudar o valor do array numpy, o que acontecera com o tensor pytorch?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [94]:
# Tensor para array numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [95]:
numpy_tensor.dtype

dtype('float32')

In [96]:
# Mudando o tensor, o que acontece ao "tensor  numpy"?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reprodutibilidade (tentando eliminar o estado aleatorio(random))

Resumindo, como a rede neural aprende é:
`Começar com números aleatórios -> operações de tensores -> atualizar números aleátorios para torná-los melhores representações dos dados -> de novo -> de novo -> de novo...`

Para reduzir a aleatoriedade em redes neurais e Pytorch, tras o conceito de **random seed**

Essencialmente, o que a seed faz é "suavizar" a aleatoriedade


In [97]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.6058, 0.2340, 0.6080, 0.9128],
        [0.4180, 0.2881, 0.2667, 0.9231],
        [0.5749, 0.6676, 0.7290, 0.9256]])
tensor([[0.2734, 0.5791, 0.1937, 0.8732],
        [0.0394, 0.2209, 0.4842, 0.1171],
        [0.3968, 0.4580, 0.5945, 0.8336]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [98]:
# Criando tesnores aleatorios mas reproduziveis
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Executando tensores e objetos Pytorch em GPUs (e fazer calculos mais rapidos)

GPUs = computação mais rapida com números, graças ao CUDA + NVIDIA hardware + Pytorch trabalhando nos bastidores para deixar tudo perfeito

### 1. Obtendo a GPU

1. Fácil - Use o Google Colab para obter uma GPU gratuita(opções de melhora)
2.  Use your own GPU - exige um pouco de configuração e o investimento na compra de uma GPU, tem muitas opções... , veja esse post para ver qual opção adquirir: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Usar computação em nuvem - GCP, AWS, Azure, esses serviços permitem alugar computadores na nuvem e acessá-los

Para 2,3 Pytorch + drivers GPU(CUDA), é necessário um pouco de configuração, para fazer isso, consulte a documentação de configuração do Pytorch



In [99]:
!nvidia-smi

/bin/bash: linha 1: nvidia-smi: comando não encontrado


### 2. Checando o acesso da GPU pelo Pytorch
 

In [100]:
# Checando o acesso a GPU com Pytorch
import torch
torch.cuda.is_available()

False

Para o Pytorch, já que ele é capaz de executar computação na GPU ou CPU é uma pratica recomendada configurar um código independente de dispositivo agnóstico: https://pytorch.org/docs/stable/notes/cuda.html#best-pratices

Executar na GPU se disponível, senão o padrão é CPU

In [101]:
# Configurando o dódigo agnóstico de dispositivo
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cpu'

In [102]:
# Contar o numero de dispositivos
torch.cuda.device_count()

0

### 3. Colocando tensores(e modelos) na GPU

O motivo pelo qual queremos nossoos tensores/modelos na GPU, é porque o uso da GPU resulta em cálculos mais rápidos 


In [103]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [104]:
# Mover o tensor para a GPU(se disponível)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))

### 4. Movendo os tensores de volta para a CPU

In [105]:
# Se o tensor estiver na GPU, nao será possível transformar em Numpy

tensor_on_gpu.numpy()

array([1, 2, 3])

In [106]:
# Para corrigir o problema do tensor na GPU com numpy, podemos primeiro configurá-lo para a CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

tensor_back_on_cpu

array([1, 2, 3])

In [107]:
tensor_on_gpu

tensor([1, 2, 3])

### Exercícios e extra-curricular